name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: roschaefer/reusable-workflows/.github/workflows/rust-ci.yml@19d39d9f3ad2c4fc7965add1ffd5bdba47385d9e # main
    permissions:
      contents: write
    with:
      binary_name: hledger-document-check
      needs_hledger: true
      needs_fava: true
