name: PR metadata

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

jobs:
  pr-metadata:
    uses: roschaefer/reusable-workflows/.github/workflows/pr-metadata.yml@bb93bad5ab1cc573b8d0b24ef0b569efdc18d1b3 # main
    permissions:
      pull-requests: read
