name: PR metadata

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

jobs:
  pr-metadata:
    uses: roschaefer/reusable-workflows/.github/workflows/pr-metadata.yml@19d39d9f3ad2c4fc7965add1ffd5bdba47385d9e # main
    permissions:
      pull-requests: read
